### ISSUE TITLE
Bug : GetVersion is deprecated

### ISSUE THREAD

**Issue by elliotwoods** [leadedge/Spout2#10]
On Windows 8.1 the following line is deprecated and throws an error (not warning) on build:

https://github.com/leadedge/Spout2/blob/master/SpoutSDK/Source/SpoutDirectX.cpp#L545

**Comment by leadedge** [comment]
OK. There was no indication in the documentation that this would cause an error.

The function is only looking for DirectX 11 but probably could be removed or replaced. Any suggestions?

**Comment by elliotwoods** [comment]
the cleanest seems to be:

```c++
bool spoutDirectX::DX11available()
{
#if (_WIN32_WINNT >= _WIN32_WINNT_WIN8)
	return true;
#else
	return false;
#endif
}
```

Other approaches (i.e. OS API's) are now extremely long winded

**Comment by leadedge** [comment]
Ok then. Can that be "_WIN32_WINNT_WIN7" (0x0601).

Not sure why they recommend to all that trouble when there are these definitions off the shelf.

**Comment by elliotwoods** [comment]
ahh yes. i got mixed up :)
Vista = DX10
7 = DX11
8 = ??
10 = DX12

**Comment by elliotwoods** [comment]
ah well
the thing is that this only checks at compile time
so it presumes that you're running the app on the machine which you built it on

**Comment by elliotwoods** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/ms725492(v=vs.85).aspx
VerifyVersionInfo seems to be the one

**Comment by leadedge** [comment]
Thanks for that. Will look at this tomorrow. The strange thing is that there is no predicting what will be compatible. Some need DirectX 9, some need DirectX 11. So the purpose of the test is somewhat arguable. This is the reason for the DirectX mode selection utility in 2.004. Have not explored Directx 12 yet. Hopefully it won't cause any trouble but we have yet to find out I guess.

**Comment by leadedge** [comment]
"DX11available" now attempts to create a DirectX 11 device. That is the only real way to test compatibility.
