### ISSUE TITLE
I found 1-2 frame delay fluctuation when I used spout for texture transmission. How can I eliminate this delay?

### ISSUE THREAD

**Issue by chentiannan** [leadedge/Spout2#101]
I found 1-2 frame delay fluctuation when I used spout for texture transmission. How can I eliminate this delay? If you have a plan or idea, please let me know. Thank you very much.

**Comment by leadedge** [comment]
If you are using a single sender/receiver pair, you can use SetFrameSync / WaitFrameSync. There are [examples](https://github.com/leadedge/Spout2/tree/beta/SPOUTSDK/Examples/ofSpoutExample/Source) in the Beta branch for both sender and receiver.

**Comment by chentiannan** [comment]
> If you are using a single sender/receiver pair, you can use SetFrameSync / WaitFrameSync. There are [examples](https://github.com/leadedge/Spout2/tree/beta/SPOUTSDK/Examples/ofSpoutExample/Source) in the Beta branch for both sender and receiver.

There will be lost frames.
![image](https://github.com/leadedge/Spout2/assets/37989848/8363b0be-a607-4b5e-8c62-d930085356da)
![image](https://github.com/leadedge/Spout2/assets/37989848/ad3ebbdd-8ac5-409f-91ae-a221d0b2affe)

**Comment by chentiannan** [comment]
And receive will find significant jitter when receiving at a frame rate of 60 frames

**Comment by leadedge** [comment]
Event sync has been implemented by collaboration with a developer who requires sync of sender to receiver. The functions were reviewed recently to enable/disable sync and have been tested successfully. 

The examples have not been updated yet but I had a look at them regarding missed frames. In this case, sender synchronizes to the receiver. I find no missed frames unless window events interfere, such as click on the caption. Without sync enabled, there are missed frames by  just moving the mouse over the window which confirms that the sync functions are working. The new examples will include binaries for testing. 

However, the examples are OpenGL and I see Direct3D 11 in your images. I have not tested the sync methods with DirectX. To compare with OpenGL, the present method should synchronize with vertical blank 'Present(1, 0)'.

**Comment by chentiannan** [comment]
Yes, I use Direct3D 11, there are missing frames during synchronization, I think it is caused by shared textures being repeatedly written at high frame rates, above is my guess, I have not confirmed, if you complete your example, or have any suggestions for this solution, please reply to me, thank you very much

**Comment by leadedge** [comment]
Frames are not actually written for the receiver, just the handle to the texture for the receiver to read. The timing is only affected by the write and read of that handle in shared memory. If the frames are produced at 60fps, that corresponds to the OpenGL examples.

I need to reproduce the problem before I can solve it. Which application uses "SetFrameSync". Is it the sender or receiver? Are you using "Present (0, 0)" or "Present (1, 0)".

There can be other issues with the graphics driver. Is it Nvidia or something else? Is this a laptop?

**Comment by leadedge** [comment]
I tested the sync functions with the SpoutDX examples and they work correctly.

You can download the projects from [here](https://github.com/leadedge/leadedge.github.io/raw/downloads/SpoutDX_sync-examples.zip). Unzip to the "SpoutDX" folder. There is a readme file and pre-built binaries in the "Tutorial04_Sync/BINARIES" folder. 

Press and release the Space bar in each application to disable/enable sync. The receiver console will show missed frames when sync is disabled.
