### ISSUE TITLE
Windows on ARM binaries missing

### ISSUE THREAD

**Issue by hmartinez82** [leadedge/Spout2#102]
The Windows SDK now has OpenGL headers again when compiling for Windows on ARM.

Spout2 should now be able to be built for Windows on ARM for DirectX 11, DirectX 12 and OpenGL (DirectX 9 is not supported for targeting native Windows on ARM)

**Comment by leadedge** [comment]
Thanks @hmartinez82. That's good to know. I am not sure if the Spout library will work for ARM. I can't test this but others may do so.

**Comment by hmartinez82** [comment]
I'll try to create a PR for it.

**Comment by leadedge** [comment]
Create the pull request for the Beta branch and I will have a look at it.

**Comment by hmartinez82** [comment]
Oh. Lots of SSE being used here, this will take a bit longer.

**Comment by leadedge** [comment]
Ok I thought it was just the CMake files. The problem is that I can't test it and so can't support the changes in the library.  I am interested to have a look at what you have done. Do you have this in a repository?

**Comment by hmartinez82** [comment]
Yes, I have a fork. I already got it setup. Using CMake to generate the Visual Studio projects for ARM64  is really simple. 
I'm looking at how to handle the SSE instructions and the __movsd intrinsic (that is x86 and x64 only)

**Comment by leadedge** [comment]
Maybe could use a conditional memcpy. It won't affect it much.

**Comment by hmartinez82** [comment]
Here's a first Go at it
https://github.com/leadedge/Spout2/pull/104

How can I test the binaries? I have a Windows Dev Kit  and a Surface Pro 9. Both are Windows on ARM
