### ISSUE TITLE
Recommended API and method

### ISSUE THREAD

**Issue by bylee20** [leadedge/Spout2#108]
I am working with Qt and it provides various graphics backends including OpenGL and Direct3D 11/12.
As a starter, which graphics backend do you recommend?
Also, I found that I can send not only texture but also fbo or backbuffer directly. Is there benefitto use those instead of texture?

Thank you for great project.

**Comment by PLEXtream** [comment]
Thank you for detailed answer!

**Comment by whiteeat** [comment]
Is it possible to use DirectX 12 API to share textures between processes without relying on D3D11on12 in the future update of this repo?

**Comment by leadedge** [comment]
Not without replacing the DirectX 11 shared textures and the OpenGL/DirectX interop. There might be a way using external memory but I have had no success.
