### ISSUE TITLE
x64 + OpenGL app + not USE_GLEW

### ISSUE THREAD

**Issue by black-sire** [leadedge/Spout2#11]
in SpoutGLextensions.cpp lines 145 - 161 load extensions for FBO you have:
glBindFramebufferEXT = (glBindFramebufferEXTPROC)**(unsigned)**wglGetProcAddress("glBindFramebuffer");

unsigned=unsigned int - it's 32 bit type. It breaks address of x64 function.

**Comment by leadedge** [comment]
Yes we found that recently on the Spout forum after a segmentation fault when using glGenFramebuffersEXT. The whole FBO section is copied from the Freeframe SDK which is 32 bit. I don't know why the cast is there in the first place.

I am almost finished with the next release which has some significant changes, so the corrections will be included in that. I have not had time to update individual files. I will look at that directly.

**Comment by leadedge** [comment]
Amended file is now uploaded. For the rest there are too many changes to revise individual files. I am aiming for  early next year for 2.005 release.
