### ISSUE TITLE
Getting nullptr textures with spout receiver

### ISSUE THREAD

**Issue by fortminors** [leadedge/Spout2#110]
Hello! I am trying to figure out a weird problem that I face when moving a working solution from PC (rtx 4060ti) to my laptop (rtx 2060 max Q).

I am in the process of receiving Spout texture from any sender and processing it. I've tried both with my custom Spout Sender and the demo SpoutSender.exe.

I basically do the following in the main loop of the receiver:

```
while (true)
{
	std::string sender_name = receiver.GetSenderName();
	bool is_connected = receiver.IsConnected();
	bool is_updated = receiver.IsUpdated();
	std::cout << "Spout Sender: " << sender_name << std::endl;
	std::cout << "Spout is_connected: " << std::to_string(is_connected) << std::endl;
	std::cout << "Spout is_updated: " << std::to_string(is_updated) << std::endl;
	if (receiver.ReceiveTexture())
	{
		dx_texture = receiver.GetSenderTexture();
	}
	else
	{
		std::cout << "Failed to receive texture" << std::endl;
	}
}
```

And I always get `receiver.ReceiveTexture() == false`.
I also notice the following logs:
```
[error] spoutDirectX::OpenDX11shareHandle (0x0002582) failed : error = 87 (0x0000057)
[warning] SpoutReceiver::ReceiveSenderData - could not retrieve sender texture from share handle
```

And as far as I understand, they come from [here](https://github.com/leadedge/Spout2/blob/master/SPOUTSDK/SpoutDirectX/SpoutDX/SpoutDX.cpp#L2214) in the source code

The same build works perfectly on my PC, but shows this weird behavior as above on my laptop.

Is there any reason you can think of, that might result in this problem?

**Comment by leadedge** [comment]
If it works in a desktop but not on the laptop, my first guess is that the laptop has a separate GPU for power saving. OpenDX11shareHandle fails if the sender and receiver are using different graphics adapters.

There are some diagnostics in the receiver popup "SpoutPanel". Click on the texture details and it should show the graphics adapters and the one the sender is using.

"IsUpdated()" is normally placed immediately after "ReceiveTexture" if update of a local texture is required. In this case it will work OK in the loop.

**Comment by fortminors** [comment]
Got it, thank you for the information!

**Comment by fortminors** [comment]
It works! SpoutPanel shows that the sender was using AMD integrated gpu, instead of discrete nvidia gpu, while the receiver was trying to connect via discrete gpu. I fixed it by adding the following line to the sender:

`m_sender.SetPreferredAdapter(DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE);`

**Comment by leadedge** [comment]
That's a positive outcome. It's good to see that the SpoutPanel sender GPU detection works as intended. I have some ideas for extending this to show both receiver and sender GPU.

**Comment by fortminors** [comment]
Looking forward to the new features! Thank you for your great work.
