### ISSUE TITLE
Questions about SpoutDX and SPoutDX12

### ISSUE THREAD

**Issue by whiteeat** [leadedge/Spout2#116]
When I compile the SpoutDX12.h and SpoutDX12.cpp, it gives me the following error:
![image](https://github.com/user-attachments/assets/83e8ca45-ed17-44b2-a182-99ac406e9300)

The fix is simple, just change it to nullptr. Will this error be fixed in the future at this repo?

Also, I discovered that each SpoutDX object contains its own spoutSenderNames, which seems problematic when setting multiple senders in my application. Should I write custom code to manage multiple senders using a single Spout sender?

**Comment by leadedge** [comment]
Yes that's a typo and will be corrected. Strange that Visual Studio shows no errors for this even with All warnings enabled.

Sender names are independently held as a set in shared memory and each instance of spoutSenderNames will access this same memory map using it's named mutex. Mutliple senders require multiple SpoutDX objects. There can't be more than one sender per object.

**Comment by whiteeat** [comment]
Thanks for the information! I studied the code further, and you are correct.

**Comment by leadedge** [comment]
FYI 
Following up on further interest in this, I have made CMake changes to create a SpoutDX12 library and an example project which seems to work OK. Let me know if this is of any use for you or if there are any problems with the idea.

**Comment by whiteeat** [comment]
> FYI Following up on further interest in this, I have made CMake changes to create a SpoutDX12 library and an example project which seems to work OK. Let me know if this is of any use for you or if there are any problems with the idea.

That's really helpful! Now I don't need to provide additional explanations to my team on how to use Spout with DirectX12!

**Comment by leadedge** [comment]
That's good news. It's useful for me to know your application and _Does it work_! 

I am updating the TUTORIAL04 example for a dll/static library which will be common process for all the libraries.
