### ISSUE TITLE
Spout2 suddenly not working in obs

### ISSUE THREAD

**Issue by WatashiwaJi96** [leadedge/Spout2#118]
I used spout2 for Vtube studio. And it suddenly stop working since yesterday. It works fine before and now i cant use it. please help me.

**Comment by leadedge** [comment]
Can you provide more information.

Are you developing your own application or using existing applications ?

If you have a coding problem can you be more specific?

If there is no code problem, the [Spout Discourse Group](https://github.com/leadedge/Spout2/issues/118) is the best place to seek assistance for problems such as this.

**Comment by leadedge** [comment]
Have you had any progress on this?
There has to be a reason for this happening suddenly.
For a start could you let me know the system details.

**Comment by leadedge** [comment]
I assume this has been resolved, so I will close the issue. Please feel free to seek assistance on the Spout Discourse group.
