### ISSUE TITLE
Receiver getting blank image

### ISSUE THREAD

**Issue by smokhov** [leadedge/Spout2#13]
@leadedge I have a multiprocess Windows 8.1 C++ application sending either texture or frame in GL_RGB, not inverted, 1024x512. The receivers getting blank black frames; no errors, receiving dimensions are correct, but when I render no image is present. I am trying to determine the cause. Spout 2.004 SDK, VS2015. I've been eyeballing Spout SDK ref manual for a while to try to understand what may be wrong. I will add more instrumentation, but if you have any ideas of that's "something typical", it'd be appreciated.

**Comment by smokhov** [comment]
(Discussion moved to http://spout.zeal.co/forums/topic/receiver-getting-blank-image/)

**Comment by leadedge** [comment]
SendImage now takes account of the host fbo binding
