### ISSUE TITLE
Rare crash on spoutDirectX::SetAdapter()

### ISSUE THREAD

**Issue by Qlex42** [leadedge/Spout2#17]
Hi 

I found a rare crash on spoutDirectX::SetAdapter()
In file SpoutDirectX.cpp at line 607
if CreateDX11device() fail, the if (pd3dDevice == NULL) is true and the following line crash:
pd3dDevice->Release();

This line could be removed because if CreateDX11device fail, nothing need to be released.

Thanks for your concern about this.

**Comment by leadedge** [comment]
OK thanks. I think it needs to be moved below or else the test device is not closed. Try it.

I found the bug in the DX9 section above as well.

**Comment by Qlex42** [comment]
Indeed, the pd3dDevice->Release(); should be moved after the else block, this fix the crash and prevent a leak. Good point.

**Comment by leadedge** [comment]
OK the memory leak explains the crash. Otherwise I was wondering why it was failing.

**Comment by leadedge** [comment]
pd3dDevice->Release() moved to the right spot.

**Comment by Qlex42** [comment]
Great thanks.
