### ISSUE TITLE
glCheckFrameBufferStatusEXT error in writeGLDtexture

### ISSUE THREAD

**Issue by SirDifferential** [leadedge/Spout2#21]
We're using Spout  2.006 on a [Intel Skull Canyon](http://www.intel.com/content/www/us/en/nuc/nuc-kit-nuc6i7kyk-features-configurations.html) with Intel i7-6770 (skylake), Intel Iris Pro 580 1024MB, Windows 10 Pro. GPU driver version is 21.20.16.4534 October 2016, OpenGL 4.4 is supported. OpenGL extension viewer displays `WGL_NV_DX_interop` as supported.

When calling `SpoutSender::SendImage()` or `SpoutSender::SendTexture()` Spout outputs `GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE_EXT (dec: 86182, hex: 0x8d56)` in SpoutGLDXinterop.cpp at `spoutGLDXinterop::WriteGLDtexture()` after calling `glCheckFramebufferStatusExt()`. This happens on both of our used textures of size 512x424 and 1920x1080. This is with DX9 being used. In our program we create an OpenGL 3.2 context.

The code works on different computers with NVidia 1060 GTX and NVidia 750m.

If we try the Spout demo sender, the texture is shown in the window. Spout demo receiver does not get the texture. The demo receiver/sender use DX9.

**Comment by leadedge** [comment]
GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE_EXT is commented out in the function PrintFBOstatus. I can't recall now the problem I had with it. Try removing it. 

But the fact that the Spout Demo receiver does not get the texture from the sender indicates a possible driver issue. Try using "SpoutDXmode" and select "CPU texture mode". Test again with the demo sender and receiver. Also try "Shared Memory". Success or failure with these will narrow it down.

**Comment by SirDifferential** [comment]
CPU mode works.

I changed https://github.com/leadedge/Spout2/blob/master/SpoutSDK/Source/SpoutGLDXinterop.cpp#L1644

from

```	if(status == GL_FRAMEBUFFER_COMPLETE_EXT) {```

to

```	if(status == GL_FRAMEBUFFER_COMPLETE_EXT || GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE_EXT) {```

and the textures appear to be transferring correctly. No errors are logged. I'm noticing an occasional hickup in the framerate, but I have yet to figure out if this is Spout or not.

**Comment by leadedge** [comment]
I recall a similar problem a while back with Unity where switching to DX11 solved an antialiasing problem which could have been due to multisampling. 

It is discussed for DirectX 9 in the specification document. Look at the DISCUSSION section and the example code -
http://developer.download.nvidia.com/opengl/specs/WGL_NV_DX_interop.txt

But it is not mentioned in the DirectX 11 equivalent -
https://www.khronos.org/registry/OpenGL/extensions/NV/WGL_NV_DX_interop2.txt

I don't know the significance of this in your application but maybe it might give you some ideas.

**Comment by SirDifferential** [comment]
The Intel control panel has application specific options under the "3D" page that include CMAA aliasing, MSAA aliasing and anisotropic filtering. I played around with all those settings with DX9 enabled, but couldn't get anything displaying.

As far as our case is considered using DX11 solves this issue.

**Comment by leadedge** [comment]
OK then. I think it is in the too hard basket. May we close this issue?
