### ISSUE TITLE
using the FFGL plugin

### ISSUE THREAD

**Issue by rwebber** [leadedge/Spout2#25]
I sometimes get an ERROR dialog, "Cannot create DirectX/OpenGL interop".
This error reopens if I click OK to close it.. and basically I am stuck.
Seems to occur sometimes when the Spout source has been closed and reopened during a Spout connection.
If this error is unavoidable, it would be better I think to fail quietly rather than locking up with the dialog. 
Again, I don't know whats possible here, just letting you know about it.
If you want me to run some tests.. let me know.

**Comment by leadedge** [comment]
Yes that messagebox is intrusive. I have an error reporting system in the works but it is a while away. If this is preventing your work I can re-compile without it. But it indicates an unrecoverable error and the problem could be in the plugin itself. When I get a moment I will have a look at it. Meanwhile can you reproduce the problem in Resolume for example?

**Comment by leadedge** [comment]
OK I think I have found something.

The plugin does nothing if ReceiveTexture fails. If the sender closes, ReceiveTexture just keeps failing until the sender is started again. 

But this has to be the same sender. If another one is started instead, ReceiveTexture will be looking for the original one and will not find the new one. I don't know why the error you mention occurs, but I think the solution could be to close the receiver if ReceiveTexture fails. Then it starts again.

I have sent you a test file by Google drive. It has a console that reports the connected sender so you can see what is happening. Try this and let me know if the error is solved.

**Comment by rwebber** [comment]
This is a hard one to repeat. Only seems to occur when you least expect it. 
In any case, I can't cause it right now purposely. 
I did, however, have it occur the very first time I launch with the new dll.
The console reported an Error 1 and Error 3 a couple of times (as I opened and closed the sender I believe).
I didn't get the exact console text because I felt it wasn't a well-controlled test, so I closed everything and started clean, of course, unable to reproduce the error.
I will continue to work with the new dll, and let you know if some useful information is given.

**Comment by leadedge** [comment]
These things are difficult to trace. I think the function "CreateInterop" is still failing for some reason.

In any event the plugin needs to be corrected, but it seems that this is not the problem.

**Comment by leadedge** [comment]
Although the cause of this error is unclear, the plugin has been updated with the most obvious problem and is in the updated installation. I believe it is related to the system and driver. If ever we get to the bottom of it then it should be reported here.
