### ISSUE TITLE
Cannot create DirectX/OpenGL interop

### ISSUE THREAD

**Issue by GitHub-bigT** [leadedge/Spout2#27]
Hi
Can u tell me how to use SpoutCam , i can't use it.
first i'm install 32bit VLC(64bit don't detect SpoutCam)
in VLC , i'm choose SpoutCam , but it black.
I open SpoutSender.exe in DEMO , VLC tell me Cannot create DirectX/OpengGL interop.

**Comment by leadedge** [comment]
The Spout support forum (http://spout.zeal.co/forums/forum/spout/support/) is the best place to find answers for this. If you go to the Search page and search - Cannot create DirectX/OpenGL interop - you will get many topics. This topic could be relevant - http://spout.zeal.co/forums/topic/resolume-arena-5-to-vlc-issue/. Try these things and open a topic on the forum if you still have problems.
