### ISSUE TITLE
how to send a grayscale image ?

### ISSUE THREAD

**Issue by avilleret** [leadedge/Spout2#36]
For performance reason I don't wan't to convert my grayscale image to RGBA color.
How can I send this image with Spout ? 

I tried :

        QImage image(m_frame.data,
                 m_frame.cols,
                 m_frame.rows,
                 QImage::Format_Grayscale8);
         m_spoutSender.SendImage(image.bits(), image.width(), image.height(), GL_LUMINANCE);

where `m_frameè  is a `cv::Mat`.
My QImage is correctly displayed in Qt, but the Demo SpoutReceiver remains black while it does detect my sender.

When I remove `GL_LUMINANCE` I do have some image on SpoutReceiver, but look like it is expecting an RGBA.

How can I solve this ? 

Thanks

BTW I tried both version 2.006 and https://github.com/leadedge/Spout2/commit/46924e3f1a81a4cf6078ec44b132e01d440e2be1

**Comment by leadedge** [comment]
Texture formats are limited by the GL/DX interop extension. The specifications do not specifically describe DirectX formats other than an example using D3DFMT_A8R8G8B8, so I tried every format possible by trial and error. This is a while back now but the results for 8 bit formats are documented in "SpoutSDK.h". Final supported formats are documented in "SpoutGLDXinterop.cpp". On the OpenGL side the format has to match, so GL_RGBA is used throughout.

**Comment by leadedge** [comment]
I should add that SendImage supports OpenGL RGBA, BGRA, RGB, and BGR if that is any help.

**Comment by avilleret** [comment]
I think there should be a way to send grayscale texture, because converting frame at 1280x1024@240fps is annoying :-)

Moreover when I send this texture as a regular colorful texture, I receive some data on the other side but they are taken as a color image and thus wrongly unpack.

So one workaround I see to the DX limitation (if it still exists) is to send grayscale texture as color texture but add some meta data to say the receiver this is a grayscale image and it should process it differently.

I don't know how metada (resolution for instance) are passed to the receiver nor if there is such a communication channel with SPout

**Comment by leadedge** [comment]
From tests I have made, the GL/DX interop does not support luminance format. The only way is to convert using OpenGL methods and I have thought more about this.

In your case, you need to send image pixels and not a luminance texture. So if you create an rgba texture you should be able to fill it with the luminance image data using [glTexSubImage2D](https://docs.microsoft.com/en-us/windows/desktop/opengl/gltexsubimage2d) .

glBindTexture(GL_TEXTURE_2D, rgbaTexID);
glTexSubImage2D(GL_TEXTURE_2D, 0, 0, 0, width, height, GL_LUMINANCE, GL_UNSIGNED_BYTE, (GLvoid *)pixels);
glBindTexture(GL_TEXTURE_2D, 0);

Then use SendTexture with the RGBA texture.

If that works, SendImage could be modified to accept GL_LUMINANCE. I am committed to other work at the moment, so can't investigate this right away but will put it on the list.

**Comment by leadedge** [comment]
Also you might need to add -

glPixelStorei(GL_UNPACK_ALIGNMENT, 1);
   - - - - -
   - - - - -
glPixelStorei(GL_UNPACK_ALIGNMENT, 4);

**Comment by avilleret** [comment]
thanks a lot, it works !

**Comment by leadedge** [comment]
OK. I will look at what is involved to add it to the SendImage function. Meanwhile I will close this as resolved.
