### ISSUE TITLE
how to send irregular sized texture ?

### ISSUE THREAD

**Issue by avilleret** [leadedge/Spout2#37]
I'm trying to send a QOpenGLWidget framebuffer texture with spout.
Since this widget can be resized by the user, its size is uncommun, something like 652 x 519.

When I try to send this texture from Qt with 

    GLuint tex = defaultFramebufferObject();
    if(tex && m_tex_width > 0 && m_tex_height > 0)
    {
      m_spoutSender.SendTexture(tex, GL_TEXTURE_RECTANGLE, m_tex_width, m_tex_height);
    }

Demo SpoutReceiver detect the sender but the screen remains black.

When I change `GL_TEXTURE_RECTANGLE` to `GL_TEXTURE_2D` I got error on sender side : 

    GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS_EXT - width-height problems?

Do you know guys how to solve this ?

Thanks

**Comment by leadedge** [comment]
it appears from this code that "defaultFramebufferObject()" is an fbo rather than a texture.

There may be a texture attached to the fbo, but this will not work with the SendTexture function. I have not considered a function to take an fbo input but will think about it.

**Comment by leadedge** [comment]
I am not familiar with QT, but it seems to me that you might need to create a texture and then load it from the framebuffer.

glBindTexture(GL_TEXTURE_2D, myTexture);
glCopyTexSubImage2D(GL_TEXTURE_2D, 0, 0, 0, 0, 0, width, height);
glBindTexture(GL_TEXTURE_2D, 0);

Then use that texture in SendTexture.

**Comment by avilleret** [comment]
this is my mistake, I'm not familiar with OpenGL and I was thinking I can pass an FBO as a regular texture.
I'll try what you suggest asap.
Thanks

**Comment by leadedge** [comment]
There is example code to create a texture in the Openframeworks sender example - 

https://github.com/leadedge/Spout2/blob/master/SpoutSDK/Example/ofSpoutExample/src/ofSpoutSender/Graphics/ofApp.cpp

**Comment by avilleret** [comment]
thanks again ! this works too !

here is the code I use :

      glBindTexture(GL_TEXTURE_2D, m_texture);
      glCopyTexSubImage2D(GL_TEXTURE_2D, 0, 0, 0, 0, 0, m_tex_width, m_tex_height);
      m_spoutSender.SendTexture(m_texture, GL_TEXTURE_2D, m_tex_width, m_tex_height);
      glBindTexture(GL_TEXTURE_2D, 0);

where `m_texture` is a GLuint created with the init function from Openframeworks example

**Comment by leadedge** [comment]
That's good. This is resolved too. I looked at adding support for SendFbo or similar but it's probably not worth the complication.
