### ISSUE TITLE
DX11 Sender not working on Windows 8.1

### ISSUE THREAD

**Issue by soraryu** [leadedge/Spout2#4]
No matter what I try (sending from DX9/DX11), I can't get sharing to work on Windows 8.1.
I'm using the Unity plugin from Ben Kuper (https://github.com/benkuper/Unity-Plugins), and, interestingly, sharing FROM Unity TO another instance of Unity does work. Only the SpoutSDK samples do not work, even after recompiling. I see them in the receiver list, but selecting just does nothing.

Here's the System Capabilites output:

Spout Receiver - DirectX 11
Windows 8 - 32bit
Intel(R) HD Graphics 5000
Driver : 39.60 (32 bpp)
Compatible hardware
NV_DX_interop extensions supported
Interop load successful
Texture sharing mode available
FBO blit available

**Comment by sorob** [comment]
make sure you download and compile the latest code. Remember that Unity Editor runs in 32 bit so make sure you compile for 32bit architectur. Also your other application must be running in 32bit as well.

**Comment by soraryu** [comment]
Of course I did all of that. Also double-checked now. I think the problem might be with the Intel HD Graphics and the DX/OpenGL interop, because DX11 texture sharing per se does work fine (tested that without Spout).

**Comment by leadedge** [comment]
Several people have reported problems with Intel graphics for Spout using DirectX 11, but it seems to work OK for Spout apps compiled to use DirectX 9. 

I have updated the Spout GitHub with the latest demo programs compiled for both DirectX 9 and DirectX 11. The demo programs use the GL/DX interop extensions, so to test this theory, run the relevant sender/receiver pairs for both DirectX 9 and DirectX 11.

If you find that SpoutDX11sender and SpoutDX11receiver still do work, then there is some other problem we need to discover.

**Comment by soraryu** [comment]
Yeah, DX9 indeed does work fine; problem is that the sender I want to receive only does DX11 for now (the current Unity3D sender implementation). I'll test your updates today or tomorrow and let you know the results, thanks!

**Comment by leadedge** [comment]
Thanks, it is good to know that.

Just for my benefit when you try these updated demo programs, even if the DirectX 9 ones work, could you please confirm that SpoutDX11sender and SpoutDX11receiver together do NOT work on your system.

Also you might find that a DirectX9 sender is received OK by a DirectX 11 receiver. It is valuable for me to know whether this works or not.

**Comment by benkuper** [comment]
Hi soraryu,
there may be a solution with OpenGL, but it would need some refactor in the native code. As DX11 is the main renderer for unity now, i didn't spent time on OpenGL support but if i get time i will look into it.
There is a new repository for Spout/Unity called "Spout4Unity" which will be the official repo as of now.

**Comment by leadedge** [comment]
Solution has to be on the application side to use DirectX 11 when necessary.
