### ISSUE TITLE
2.006 and 2.007 beta compatibility issues

### ISSUE THREAD

**Issue by bigt1234** [leadedge/Spout2#44]
Hello,

What should I do if I want to integrate the d3d11 receiver into the old project (2.006)?

Replace all files with those in the 2.007 beta branch? Will the old opengl receiver still work?

Looking forward to your reply, thank you!

**Comment by leadedge** [comment]
2.007 retains all the 2.006 functions, so if you replace the entire SDK, your OpenGL application should still build and work as before. Of course being a beta test version there could be bugs, but from testing it appears to be stable.

**Comment by bigt1234** [comment]
thanks!
