### ISSUE TITLE
Spout SDK compatibility with C++/CLI

### ISSUE THREAD

**Issue by microdee** [leadedge/Spout2#45]
Unfortunately Spout SDK cannot be compiled with C++/CLI as it has `using namespace std;` at couple of places which will result in name collisions between managed types and std:: things. It's only a nuisance and it's only important if I'd like to avoid distributing the spout dll and p/invoking with it. I can report more once I test out the new beta again.

**Comment by leadedge** [comment]
Yes thanks. I had that advice about not using the std namespace before and I thought I had removed it. But now that you mention it I will go through it again.

**Comment by leadedge** [comment]
Fixed during cleanup check
