### ISSUE TITLE
Does Spout work in Unity when using HDRP ?

### ISSUE THREAD

**Issue by timwei919** [leadedge/Spout2#50]
Hello,
I am using Unity's Visual Effect Graph function,
To use this function, it must be under HDRP.

So I would like to ask if Spout can be executed in this situation?
Because I add the spout sender component on Camera (like the way we are familiar with),
However, the image cannot be transmitted.

So I would like to ask if Spout(Not even NDI) can run under HDRP? is there any other reason?

Thanks!

**Comment by leadedge** [comment]
That's not something I could advise on. But I note that Keijiro has a comment in KlakSpout.cpp

// Do nothing if it's not the D3D11 renderer

I believe that he is the expert who may answer this question.

**Comment by timwei919** [comment]
Thank you very much for your assistance, I have found a solution

**Comment by leadedge** [comment]
OK I am glad that Keijiro could help you.
