### ISSUE TITLE
readme.pdf confusing for new users

### ISSUE THREAD

**Issue by nuclearsugar** [leadedge/Spout2#51]
Within the recently released Spout_2006_update-3.zip on [download page](https://leadedge.github.io/spout-download.html), the `readme.pdf` puts much focus on how to upgrade from a prior Spout install. Over within the NestDrop community, we have new users which are installing Spout for the first time and are confused of how to correctly install Spout.

Would you consider splitting up the installation instructions into 2 sections _(first-time install & upgrading)_ within the `readme.pdf`?

**Comment by nuclearsugar** [comment]
Also a related thought. Within the readme.pdf it would be helpful to suggest where the Spout folder could be manually installed to. The easiest perhaps being <C:\SPOUT-2006_UPDATE-3>.

**Reasoning**
- Should the user register Spout from the Download or Desktop folder and yet not realize that it's been permanently registered to this location, it could cause problem for when they forget and happen to delete it later on.
- The SpoutReceiver.exe is so useful. And so within the NestDrop documentation we refer to the default file path of the SpoutReceiver.exe.  (and I'm sure other documentation does also).

**Comment by nuclearsugar** [comment]
I realized that splitting up the installation instructions into 2 sections was probably redundant. But I edited and polished the text to be more understandable for a first-time user. I also created a section for the Uninstallation Instructions and moved some details there.

Hope it's helpful. Cheers!

-----

**Spout**
Spout 2.006 Update 3 contains revised utility programs ready for the upcoming 2.007 release. The backup CPU sharing mode option has been removed due to no advantage over Memory sharing. The source for this will be removed from the Spout 2.007 SDK.


**Installation Instructions**
The ‘SPOUT-2006_UPDATE-3’ folder can be moved to any folder. Avoid folders that require administrator privileges. A recommended location is _<C:\SPOUT-2006_UPDATE-3>_

After you’ve moved the Spout folder to a permanent location, you will need to initialize Spout with the following steps:

**1) Uninstall prior versions of Spout**
If you have a prior version of Spout already installed, then use the Windows Control Panel or the Spout uninstaller _<C:\Program Files (x86)\Spout2\unins000.exe>_

**2) SpoutCam**
Run _<SPOUTCAM/SpoutCamSettings.exe>_, click register, and then close the window.

**3) Settings**
Run _<SPOUTSETTINGS/SpoutSettings.exe>_, choose the settings you require, and click OK to automatically save the settings into the Windows registry.

**4) SpoutPanel**
Run _<SPOUTPANEL/SpoutPanel.exe>_ and then close the window without any changes. This will automatically make a link within the Windows registry. To confirm that it’s working properly, run the _<DEMO/SpoutReceiver.exe>_ and right-click on the window and the SpoutPanel should appear.

**5) Visual Studio 2017 runtimes**
The Spout utility programs are built with Visual Studio 2017. So if you’re seeing errors about missing DLL’s then must download and install the [Visual Studio 2015, 2017 and 2019 runtimes](https://support.microsoft.com/en-au/help/2977003/the-latest-supported-visual-c-downloads). Spout programs can run using either 32-bit or 64-bit, so you need to install both runtimes separately. Please be sure to install the 64-bit version before the 32-bit version.

**6) Shortcuts**
Consider making shortcuts on your desktop to the Demo programs and SpoutSettings.

**7) Documentation**
The documentation will soon be updated with the upcoming Spout 2.007 release. Please direct any questions to the [Spout Discourse group](https://spout.discourse.group/).


**Uninstallation Instructions**
Run _<SPOUTCAM/SpoutCamSettings.exe>_, click register, and a prompt will be shown with more info to unregister it.

If you want to remove Spout and clean the registry, use Regedit to delete :
_<HKEY_CURRENT_USER\Software\Leading Edge\Spout>_

Or if there are no other Spout applications installed, use Regedit to delete :
_<HKEY_CURRENT_USER\Software\Leading Edge>_

**Comment by leadedge** [comment]
Many thanks for your attention and time with this. I will use your proposed changes in a revision. The main reason for doing this was that the installer was being rejected for download and installation by both Windows defender and anti-virus programs, so it had to be done quickly. The other reason was blocking of the programs themselves to write ini files etc due to lower privileges. I am thinking about alternatives to make it more simple, so some sort of installer or other means could return. Perhaps a new one with Inno setup and the manual method as backup. The hurdle is the requirement for a certificate.

**Comment by nuclearsugar** [comment]
I figured there was a reason behind the installer change. Hope you are able to figure out a solution. Certificates are such a pain.

Happy to help. Cheers!
