### ISSUE TITLE
SpoutReceiver.exe /// full screen

### ISSUE THREAD

**Issue by nuclearsugar** [leadedge/Spout2#52]
When using the SpoutReceiver.exe application, the full screen option will always use the 'main display' (determined in the Windows display settings). 

Would it be possible to instead full screen to the monitor that the SpoutReceiver.exe window is currently located within?

- I've searched extensively for a alternative Spout Receiver that can simply full screen a Spout stream to a specific monitor, but it doesn't exist on Github or such.
- It would be particularly useful for performers that need a quick way to full screen a Spout stream, without needing to rely on Resolume or such mapping software. Also since multiple instances of the SpoutReceiver.exe can be running at once, then the user could full screen a unique Spout stream to each monitor/projector.

**Comment by leadedge** [comment]
This was addressed back in 2017 by [Tim Thompson](https://github.com/nosuchtim), who changed the full screen function to allow for multiple monitors. It required some changes to use (MonitorFromWindow). If it's on a different monitor this function detects it. Default is the primary monitor. I can't see any changes since then that might affect it. Unfortunately I can't test it because I don't have a multiple monitor setup. 
Check the version you are using. The changed occurred for Version 2.019. The latest version is 2.024. At that time it worked for him, so it should be same now. It might be possible with Openframeworks or something similar, but again I don't have the means to do anything with it. Perhaps you know somebody who might be able to help.

**Comment by nuclearsugar** [comment]
Thanks for the info. 

I'm using SpoutReciever v2.023, as bundled with the latest [Spout_2006_update-3 Install](https://github.com/leadedge/leadedge.github.io/raw/downloads/Spout_2006_update-3.zip). Unfortunately SpoutReciever will currently only use the main display for full screening. This is confirmed from several different people using multi-monitor setups.

@nosuchtim - Would you be interested and willing to look at the SpoutReciever code again?

**Comment by leadedge** [comment]
2.024 is at https://github.com/leadedge/Spout2/tree/beta/DEMO. But I am sure it won't make any difference.\
If Tim has the time, I am available by email to look at details.

**Comment by leadedge** [comment]
Try this version - 2.021 -

[SpoutReceiver.zip](https://github.com/leadedge/Spout2/files/4868062/SpoutReceiver.zip)

 just after the modifications were made:

**Comment by nuclearsugar** [comment]
I just tested out SpoutReciever v2.021 and it will only use the main display for full screening. So perhaps something within Windows or a library has changed since then. Alas!

**Comment by leadedge** [comment]
Here is Version 2.020

[SpoutReceiver_2020.zip](https://github.com/leadedge/Spout2/files/4871958/SpoutReceiver_2020.zip)

That goes back a little more. I can't find 2.019.

**Comment by nosuchtim** [comment]
The SpoutReceiver.exe in SpoutReceiver_2020.zip seems to work fine with
multiple monitors and fullscreen - I just invoked it and was able to
fullscreen it on one monitor, then move it to another monitor, and do a
fullscreen there (without exiting).

I'm not sure I have the current source for SpoutReceiver anymore, and I
don't see it in the github repo.  I have the email where I sent Lynn the
changes for multiple monitor fullscreen, this was the final version of my
changes:

HMONITOR monitor = MonitorFromWindow(g_hwnd, MONITOR_DEFAULTTOPRIMARY);
MONITORINFO mi;
mi.cbSize = sizeof(mi);
GetMonitorInfo(monitor, &mi);
SetWindowPos(g_hwnd, HWND_TOPMOST,
mi.rcMonitor.left,
mi.rcMonitor.top,
mi.rcMonitor.right - mi.rcMonitor.left,
mi.rcMonitor.bottom - mi.rcMonitor.top,
SWP_SHOWWINDOW);
SetMenu(g_hwnd, NULL);


     ...Tim...

**Comment by leadedge** [comment]
Thanks very much Tim.
The menu is now removed and the TaskBar put lowest order before the resizing.
Could you try both 2.021 and 2.024?
This should confirm where the problem is.
There is no repo for this, but I can send you a complete project for Visual Studio 2017.

**Comment by nosuchtim** [comment]
Neither 2.021 or 2.024 work.

    ...Tim...

**Comment by nosuchtim** [comment]
By that I mean that they run, but the multi-monitor fullscreen behaviour is
broken.  2.020 works fine.

    ...Tim...

**Comment by leadedge** [comment]
Thanks Tim.
The only thing different between 2.020 and 2.021 is -
```
		GetMonitorInfoA(monitor, &mi);
		int w = (int)(mi.rcMonitor.right - mi.rcMonitor.left); // rcMonitor dimensions are LONG
		int h = (int)(mi.rcMonitor.bottom - mi.rcMonitor.top);
		// Setting topmost causes a grey screen for Windows 10
		// If scaling is set larger than 100% e.g. 125%
		// Also there seems to be a delay in receiving keystrokes even if set to 100%
		// SetWindowPos(g_hwnd, HWND_TOPMOST, 0, 0, w, h, SWP_SHOWWINDOW);
		// This seems to fix it.
		SetWindowPos(g_hwnd, HWND_NOTOPMOST, 0, 0, w, h, SWP_SHOWWINDOW);
		SetWindowPos(g_hwnd, HWND_TOP, 0, 0, w, h, SWP_SHOWWINDOW);
```
So I removed the NOTOPMOST/TOP and went back to a single TOPMOST. It no longer goes grey for me at this time. Could have been be a driver issue.

[SpoutReceiver_2005.zip](https://github.com/leadedge/Spout2/files/4872922/SpoutReceiver_2005.zip)

If that still doesn't work, I am not sure where to look.

**Comment by nosuchtim** [comment]
The 2.025 version doesn't work.

    ...Tim...

**Comment by nuclearsugar** [comment]
I tested each version and [SpoutReceiver v2.020](https://github.com/leadedge/Spout2/files/4871958/SpoutReceiver_2020.zip) is the only version that will fullscreen to any monitor.

@pom256 - have any experience with this?

**Comment by leadedge** [comment]
I think I found the problem. While I was trying to solve the grey screen effect, I forgot to include the monitor origin in the moves.
```
		int x = (int)mi.rcMonitor.left;
		int y = (int)mi.rcMonitor.top;
		int w = (int)(mi.rcMonitor.right - mi.rcMonitor.left);
		int h = (int)(mi.rcMonitor.bottom - mi.rcMonitor.top);
		SetWindowPos(g_hwnd, HWND_NOTOPMOST, x, y, w, h, SWP_SHOWWINDOW);
		SetWindowPos(g_hwnd, HWND_TOP, x, y, w, h, SWP_SHOWWINDOW);
```
[SpoutReceiver_2026.zip](https://github.com/leadedge/Spout2/files/4874275/SpoutReceiver_2026.zip)

**Comment by nuclearsugar** [comment]
SpoutReceiver v2.026 fixed the issue! Nicely done.

**Comment by pom256** [comment]
I always think that the demo receiver was designed for the main monitor only so I didn't try on a second monitor. But many NestDrop user tell me  the same as NuclearSugar regards as even if they drag the Window on the second screen, it will go back to the primary in fullscreen mode. So I just tell them that they change the main monitor in Window setup... But it's more a patch for the moment then a real fix.

I know that the real 'fullscreen' mode in Directx was targeted the main monitor only. But I remember read some comment in spout code that the fullscreen was just replaced by a floating window with the same size than the screen... But this is old stuff and I'm sure that leadedge is already far beyond that...

**Comment by leadedge** [comment]
OK @nuclearsugar. That's got it working for you.\
@pom256 - yes it's not real fullscreen. The window menu and borders are removed and the remainder is resized and put on top. This was always intended as a demo testing program and the code is ancient. There will come a time when it won't work but until then it does the job.\
I [read](https://docs.microsoft.com/en-us/windows/win32/hidpi/high-dpi-desktop-application-development-on-windows) that there is more involved with DPI and scaling, but it's going too far for this program. I have enabled "Per Monitor High DPI Aware" in the project settings, so hopefully that will look after it.\
@nosuchtim many thanks for your help.
