### ISSUE TITLE
Spout.NET for C# & .NET Framework

### ISSUE THREAD

**Issue by Afanyiyu** [leadedge/Spout2#53]
Just to help latecomers: I have ported Spout to the .NET Framework: [Spout.NET](https://github.com/Ruminoid/Spout.NET). It also provides a [Nuget package](https://www.nuget.org/packages/Spout.NET) and a Get Started Guide so you can quickly start to develop.

**Comment by leadedge** [comment]
Thankyou for this generous contribution. I made an announcement on the [Spout discourse group](https://spout.discourse.group/).
