### ISSUE TITLE
Spout DX12

### ISSUE THREAD

**Issue by sasa42** [leadedge/Spout2#55]
Hi,

would it be possible to add Spout DX12 support.
We heavily use keijiro´s Spout unity integration in Unity.
https://github.com/keijiro/KlakSpout

We have to switch to DX12 for DXR raytracing features and Spout is really missed there.

We currently use the DX12 NDI implementation
https://github.com/keijiro/KlakNDI

But Spout is faster and it fits more to our needs.

**Comment by leadedge** [comment]
Hi @sasa42

yes the same [has been asked](https://spout.discourse.group/t/unreal-plugin-fail-help/163) for Unreal Engine.

This was solved  by a plugin developed by [OffWorldLive](https://github.com/Off-World-Live/) using the D3D1211On12 feature which enabled Spout compatibility for ray tracing.

The same might be possible for the KlakSpout plugin and the author is best to advise on that. Perhaps OffWorldLive would be able to assist.

I have looked into whether D3D1211On12 could be incorporated into Spout but have only started to investigate possibilities. Currently I am working on restructure of the project which must be completed first or the foundation would not be satisfactory.

**Comment by leadedge** [comment]
I looked into this a little further. At this stage DX12 is not possible within the Spout SDK itself. Fundamentally a DirectX 11 shared texture is used, so the sending or receiving application would need to use 11-on-12 to link with it. It's something to keep in mind, along with Vulkan that has also been suggested.
