### ISSUE TITLE
Port spout to VK_External_memory

### ISSUE THREAD

**Issue by medcelerate** [leadedge/Spout2#59]
Currently there is no supported spout system on linux, and having a single cross-platform solution would be incredibly useful for a number of scenarios. We currently use linux servers for display in our studios and use it heavily in our virtual production workflow. We have solutions using spout but would love to have support on linux as well as for VJ related usings. This is why I bring up creating a version that supports Vulkan external memory to allow for copying of textures between processes without loosing the benefit of GPU texture sharing performance. 

https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_external_memory.html

**Comment by leadedge** [comment]
Using Spout with Vulkan [is possible](https://developer.nvidia.com/getting-vulkan-ready-vr) by interfacing a Vulkan image with a DirectX 11 texture. 

I am not familiar with Linux but if it's possible to use DirectX 11 and if shared textures are supported then it might be easier to use that directly. Applications can already use a sub-set of the Spout SDK classes to do this and there has been some progress with it, as you can see in the beta and develop branches. Is this a possibility?

**Comment by medcelerate** [comment]
So there is no directx on Linux, Vulkan is really where everything is
headed. So it would require swapping any directx implementations with their
Vulkan alternatives.

**Comment by leadedge** [comment]
I understand that sharing Vulkan images directly using external memory can be done and combining with the existing Spout sender name system would be the way to investigate this. 

There would need to be some synchronisation mechanisms but I expect that could be sorted out. 

But I am afraid that's some time off for me to find the time and gain the expertise to do so. Meanwhile the only solution is with shared DirectX textures if there is any possibility for you there.

**Comment by medcelerate** [comment]
I may fork the repo and better understand the code base, I’m thinking I may
be able to play with the API and see if textures can be easily copied.

**Comment by leadedge** [comment]
You might be best to go straight to the Develop branch and look at the "Basic" DirectX examples for the low level workings. The SpoutDX support class is designed to make things easier.

**Comment by leadedge** [comment]
Let's keep this option open for the future, but for now I can't immediately help with it. If you come to any potential solution, please email using the contact on this repository overview page.
