### ISSUE TITLE
Spout 2.007 : SpoutSender / SpoutSenderNames crashing

### ISSUE THREAD

**Issue by datee** [leadedge/Spout2#66]
[ Windows 10, x64 application, OpenGL application ]
For some reason i cant get SpoutSender to work. Its always crashing when it tries to set up the sender. 

I've tracked the issue down to being accessing m_senders in SpoutSenderNames. So - the spoutSenderNames::UpdateSender function will crash at : m_senders->find(namestring)  here : https://github.com/leadedge/Spout2/blob/0f88e631d5328d5e5aedef287a7f8f3076b99be3/SPOUTSDK/SpoutGL/SpoutSenderNames.cpp#L658 . The sendername seems ok - im not sure whats going on.

SpoutReceiver works just fine! Anything that could cause this?

**Comment by leadedge** [comment]
That looks OK, but maybe the equality can't be tested like that, such as an example from [documentation](https://www.cplusplus.com/reference/unordered_set/unordered_set/find/).

std::unordered_set<std::string>::const_iterator foundSender = m_senders.find (namestring);

  if ( foundSender == m_senders.end() )

Also elsewhere we have -

auto foundSender = m_senders->find(namestring);

**Comment by datee** [comment]
Seems there was a heap issue here - though the error was a bit strange i was able to fix it. Thanks!

**Comment by leadedge** [comment]
I am not sure exactly what the problem was or if other people might have the same trouble.

Is the problem isolated to your project or should I do something here. I can clean it up to use
`auto foundSender = m_senders->find(namestring);`
Also I would check for empty namestring.

**Comment by datee** [comment]
Hm, no i dont think the equality itself was the issue here, since I had crashes with all kinds of access to m_senders. (and only to m_senders). Hard to say if anyone else will have the same issue - im getting unexpected behaviour in certain scenarios when im creating a sender object on the stack here. Closed this for now until i can say for sure where the problem occurs.

**Comment by leadedge** [comment]
OK that's good information and I will look into it a little. Of course please come back if anything comes up.
