### ISSUE TITLE
RFE: get spout version as String

### ISSUE THREAD

**Issue by MikOfClassX** [leadedge/Spout2#67]
Hello,

just a little RFE: place the Spout version as global version string.

i.e. 
#define SPOUT_VERSION "Spout2 [2.007]"

or similar

This will avoid us to create a Spout object only to get the library version.

Thanks!

**Comment by leadedge** [comment]
OK that's an idea. Until now I have not numbered the library version. So I will need to think about that a little.
GetSpoutVersion() returns the number, 2004, 2006, 2007 etc.. but that refers to what the user installs at -

Computer\HKEY_CURRENT_USER\Software\Leading Edge\Spout\Version
 
It would be nice to somehow find what version a particular application used but I have not discovered how to to that.

**Comment by MikOfClassX** [comment]
Yep. Spout can indeed be compiled/linked statically to an application and there may be no install at all (which is the most frequent case imho). So a version tag is absolutely welcome.

**Comment by leadedge** [comment]
OK no problems, I am looking into it. A bit busy with other things right now though

The user can install Spout or they don't get the settings, so knowing what the user has done is a separate thing.

**Comment by MikOfClassX** [comment]
Well, maybe it would be nice to separate the 2 things, more or less what happens with NDI:
- create the official SpoutTools installer (Sender/Receiver/Settings/Panel + local dll or statically linked)
- leave developers use the SDK as they want (static, local dll, etc.)

**Comment by leadedge** [comment]
Yes that's the way to do it. NDI has a dynamic dll load independent of the SDK that applications are built with so I can examine what they do there. The trick I would like to solve is finding out what version a particular application has used.
As I say, there's a lot on my plate at the moment and I will certainly look into it.

**Comment by leadedge** [comment]
I have added "std::string GetSDKversion()" to the SpoutUtils namespace. Brief testing seems OK.

**Comment by MikOfClassX** [comment]
that's cool. Thanks!

**Comment by leadedge** [comment]
OK, that should do the job.
