### ISSUE TITLE
Spout Settings - max senders can't set to a value with more than 2 digits

### ISSUE THREAD

**Issue by Harvey3141** [leadedge/Spout2#68]
The text input field in the SpoutSettings app doesn't allow it

**Comment by leadedge** [comment]
It's a scaling problem. I have my display scaled to 125% and at 100% 3 digits don't fit. I will change for the next update. What maximum do you actually need?

Meanwhile you can edit the registry DWORD value directly :

Computer\HKEY_CURRENT_USER\Software\Leading Edge\Spout\MaxSenders

**Comment by Harvey3141** [comment]
We typically set it to 200, I don't think we've every actually exceeded 100 though, good to know about the registry setting. Thanks

**Comment by leadedge** [comment]
OK I assumed that 3 digits would be enough. If you do change the registry setting, remember that SpoutSettings will change it back to default on OK. I will close this because it's resolved but I have a couple of other changes to check before an update.
