### ISSUE TITLE
not define GLEW_STATIC

### ISSUE THREAD

**Issue by miroandel** [leadedge/Spout2#8]
Defining GLEW_STATIC kind of forces end user to use glew as a static library. I would remove this from SpoutGLextensions.h and let the programmer that uses the framework specify how to use GLEW in their projects.

**Comment by leadedge** [comment]
Just comment out GLEW_STATIC. I will do so here and leave it commented out in the distribution files.

**Comment by leadedge** [comment]
Now an option for 2.005.
