### ISSUE TITLE
Multiple Senders in SpoutDX

### ISSUE THREAD

**Issue by Tadghostal** [leadedge/Spout2#83]
I am having trouble with getting spoutdx to create a total of 4 senders. I create 4 separate instances of the Spoutdx object, OpenDX11 with nullptr, and set a sender name. All these functions return true. Then when I receive a frame from my camera system (a weird CoaXpress card by Matrox) I give SendImage a pointer to my buffer for each camera and instance of spoutdx and this also returns true. However, only the first instance of the Spoutdx is ever seen by my receivers, I tried it both with Klakspout in unity and the SpoutReceiver.exe in demos. They all play back the first instance but the names for the additional instances never show up and I know for sure SendImage is being called for all the instances and returning true. Is there something I am missing?

**Comment by Tadghostal** [comment]
So I did some more experimentation and it seems that whichever spoutdx I set sender name for first is the one that works.

**Comment by leadedge** [comment]
I just tried this with the Windows sender example and multiple senders work OK independently. The demo receiver sees four independent senders. I haven't tried it with independent images though.
It's not clear to me whether you call OpenDirectX for each sender object or only once. Could you confirm that. For each sender you need -
sender1.OpenDirectX();
sender1.SetSenderName("sender name one");
sender1.SendImage(pixelbuffer1, width1, height1);
and finally
sender1.ReleaseSender();
Repeat this for each sender, with a different name for each one.

**Comment by Tadghostal** [comment]
Yeah sorry, it wasn't an issue with your code but had to do with how the matrox software was interacting with Unity. I was able to get things to work after I discovered that, but it was the end of the day and I forgot to close the issue. Thanks for your help.

**Comment by leadedge** [comment]
No problems. Sounds like an interesting project.
