### ISSUE TITLE
CPU sharing flag is always false in OpenSpout

### ISSUE THREAD

**Issue by cansik** [leadedge/Spout2#85]
As already discussed in https://github.com/jlai/Python-SpoutGL/issues/15 it seems that DirectX CPU sharing is not working as expected in `2.007h`. I now debugged the spout code and it seems that the problem lies here:

```cpp
HDC hdc = wglGetCurrentDC();
if (hdc) {
  // Get a window handle
  m_hWnd = WindowFromDC(hdc);
  // Load extensions
  if (LoadGLextensions()) {
    // If DirectX and OpenGL are both OK - test GLDX compatibility
    // For a re-test, create a new interop device in GLDXReady()
    if (bRetest) {
      CleanupInterop();
    }
    SpoutLogNotice("spoutGL::OpenSpout - GL extensions loaded sucessfully");
    // Drop through for detail notices
  } else {
    SpoutLogFatal("spoutGL::OpenSpout - Could not load GL extensions");
    return false;
  }
} else {
  SpoutLogFatal("spoutGL::OpenSpout - Cannot get GL device context");
  // This is OpenGL, but DirectX shared textures might still work OK (see SpoutDX)
  return false;
}
```
https://github.com/leadedge/Spout2/blob/master/SPOUTSDK/SpoutGL/SpoutGL.cpp#L470-L474

If the **else** branch (`spoutGL::OpenSpout - Cannot get GL device context`) is running, it returns false and does not run through the following code which would determine if **CPU sharing** can be enabled. Remove the **return** statement fixes this behaviour but I am not sure if the is intended. Or it would also be possible to check if the `m_bAuto` (Auto Sharing) is enabled and depending on that flag return or not.

Would be great if one of the Spout2 devs could give me a hint which way to fix it so I can prepare a PR.

As a workaround I am currently setting the `SetCPUshare` to `true` after running `OpenSpout`.

**Comment by leadedge** [comment]
Thanks for your time with this. It is indeed a mistake. At line 441, the default for `m_bCPUshare` should be true.
I would be grateful if you could test and confirm before I make the change.

**Comment by cansik** [comment]
Thank you, I tested it and it is indeed the flag that needs to be changed. I have opened a PR.

**Comment by leadedge** [comment]
Again, thanks for your attention and time to find this error.

I know this is a really simple change and it shows no conflicts, but I am not merging any more pull requests right now as discussed in #84.  I will do it by hand and update master branch as soon as I can. Beta is not yet ready yet for commit yet but I will make exactly the same change in that file.

**Comment by cansik** [comment]
Ok, I am going to fix it in the [Python-SpoutGL](https://github.com/jlai/Python-SpoutGL) as well.

**Comment by leadedge** [comment]
Yet again, thanks for your time and attention.

**Comment by leadedge** [comment]
After a little more though I would suggest the following change -
```

	m_bUseGLDX = false;
	m_bTextureShare = false;
	m_bCPUshare = false;

	// DirectX capability is the minimum
	if (!OpenDirectX()) {
		SpoutLogFatal("spoutGL::OpenSpout - Could not initialize DirectX 11");
		return false;
	}

	// Default CPU share until tested
	m_bCPUshare = true;

```
There are other changes in the beta branch and that is almost ready for update to master.

**Comment by leadedge** [comment]
Change checked and confirmed for 2.007.009 update
