### ISSUE TITLE
Small code issue in SpoutGL.cpp

### ISSUE THREAD

**Issue by jcelerier** [leadedge/Spout2#87]
Around lines 2965:

```
	if (m_bPBOavailable) {
		if (!(m_caps && GLEXT_SUPPORT_PBO))
			m_bPBOavailable = false;
	}

	// Show status
	if (!m_bPBOavailable) {
		if (!(m_caps && GLEXT_SUPPORT_PBO))
			SpoutLogWarning("spoutGL::LoadGLextensions - pbo extensions not available");
		else
			SpoutLogWarning("spoutGL::LoadGLextensions - pbo functions disabled by settings");
	}
```

the tests `m_caps && GLEXT_SUPPORT_PBO` should instead be a bitwise &, no ? `m_caps & GLEXT_SUPPORT_PBO`

**Comment by leadedge** [comment]
Well spotted. Yes that's an error. This has been fixed in the beta branch, along with numerous other things.
Currently I am going through all files in the beta branch and it's almost ready for update to master.
It would be useful if you could change to that code in advance of the update.

**Comment by leadedge** [comment]
Beta is now up to date.

**Comment by leadedge** [comment]
Change checked and confirmed for 2.007.009 update
