### ISSUE TITLE
Use SendImage without using OF, Cinder, etc.

### ISSUE THREAD

**Issue by tschnz** [leadedge/Spout2#88]
Hey I want to write a minimalist C++ app that grabs images from a cam and sends them via Spout. When I try to send my unsigned char pixel buffer via SendImage it just returns false. I guess I'm missing libraries that make texture sharing work?

The Demo Receiver correctly recognizes the width and height, but doesn't receive a single image.

Help or a repo that utilizes Spout2 in a minimal approach would be awesome, I didn't find one after excessive googling.

**Comment by leadedge** [comment]
Probably the best idea is to use DirectX with "SpoutDX".

The [Windows sender example](https://github.com/leadedge/Spout2/tree/master/SPOUTSDK/SpoutDirectX/SpoutDX/Windows/Sender) should get you started.

**Comment by tschnz** [comment]
Thanks for pointing me there!
