### ISSUE TITLE
Question : Mutable `char *` for channel names

### ISSUE THREAD

**Issue by elliotwoods** [leadedge/Spout2#9]
Heya!

I noticed that you're passing `char *` as parameters for `CreateSender`, `UpdateSender`, etc.
Are you purposely choosing `char *` rather than `const char *` because you might return a different name than was passed in? Otherwise, what is the reason for not using `const char *`?

I end up having blocks of code looking like:
```c++
char * mutableName = new char[channelName.size() + 1];
strcpy_s(mutableName, channelName.size() + 1, channelName.c_str());
this->spoutSender->CreateSender(mutableName);
this->channelName = string(mutableName);
delete[] mutableName;
```
Or is it unnecessary? Should I just use a `const_cast` because the functions will never change the string? It seems strange that `UpdateSender` would ever need to change the name passed into it.

Thank you
Elliot

**Comment by leadedge** [comment]
No it not on purpose, just leftover as it has developed. They all should be either const or not. There was some attention to this when doing the SenderNames class but others have gone un-noticed. I am in the process putting the next version together so will go over it.

**Comment by elliotwoods** [comment]
Thanks. OK good to know
p.s. I knocked together a wrapper for tidyness : https://github.com/elliotwoods/ofxSpout

**Comment by leadedge** [comment]
Well done for a knock together. If you can suggest how to test for DX11 availability please let me know.

**Comment by elliotwoods** [comment]
i commented in the other issue
