### ISSUE TITLE
Add ossia to the list of Spout-compatible software :) 

### ISSUE THREAD

**Issue by jcelerier** [leadedge/Spout2#90]
in this page: https://spout.zeal.co/

ossia score: https://ossia.io

feel free to use this logo: https://github.com/ossia/score/blob/master/src/lib/resources/ossia-score.png

thanks :)

**Comment by leadedge** [comment]
Ossia score is certainly an impressive project. The logo is up on the Spout web page.

**Comment by jcelerier** [comment]
thanks a lot ! :)

**Comment by leadedge** [comment]
I made a brief post on [Spout Discourse](https://spout.discourse.group/t/ossia-score-with-spout-support/445)
