### ISSUE TITLE
Should the solutions be removed from the repo?

### ISSUE THREAD

**Issue by mbechard** [leadedge/Spout2#91]
Since there is a CMake workflow, does it make sense to remove the VS2017 projects etc from the repo to avoid confusion?

**Comment by leadedge** [comment]
Yes the VS2017 solutions are out of date and could go. The idea of a VS solution to build the dll is left over from the original Spout-1 project and isn't relevant now that  CMake has been introduced by contribution. Importantly, this  also allows other compilers to be used. Probably I would like to retain VS projects for the examples but I am looking at removing a lot of other things that are included more for convenience than anything else. There are changes accumulating in the beta branch and when that reaches a stable state I will look at trimming it down before master update.

**Comment by leadedge** [comment]
I will close this as noted. I reviewed this further and confirm that I will keep the DirectX example projects in line with the original Walbourn examples.
